---
driver:
  name: digitalocean
#driver_config:
#  digitalocean_client_id: <%= ENV['DIGITAL_OCEAN_CLIENT_ID'] %>
#  digitalocean_api_key: <%= ENV['DIGITAL_OCEAN_API_KEY'] %>

provisioner:
  name: chef_solo

platforms:
- name: centos-6-5-x64
  driver_plugin: digitalocean

suites:
  - name: default
    run_list:
      - recipe[demo::default]
    attributes:
